application: post-engine
version: 3
runtime: python
api_version: 1

inbound_services:
- mail

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt

- url: /
  script: logic/page.py

- url: /index\.html
  script: logic/page.py

- url: /feed/?
  script: logic/feed.py

- url: /entry/.*
  script: logic/page.py

- url: /admin/.*
  script: logic/admin.py
  login: admin

- url: /_ah/mail/.+ 
  script: logic/email.py 
  login: admin

- url: /.*
  script: logic/page.py